=== nonamesl95/PEI_MA01_8130372_8140176_8140211/feriados.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
    <xs:element name="feriados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="feriado" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:date" name="data"/>
                            <xs:element type="xs:string" name="nome"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nonamesl95/PEI_MA01_8130372_8140176_8140211/PEI_MA01_8130372_8140176_8140211/files/feriados.xml
<?xml version="1.0" encoding="UTF-8"?>
<feriados xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="feriados.xsd">
    <feriado>
        <data>2018-01-01</data>
        <nome>Ano Novo</nome>
    </feriado>
    <feriado>
        <data>2018-03-30</data>
        <nome>Sexta feira Santa</nome>
    </feriado>
    <feriado>
        <data>2018-04-01</data>
        <nome>Pascoa</nome>
    </feriado>
    <feriado>
        <data>2018-04-25</data>
        <nome>25 de Abril</nome>
    </feriado>
    <feriado>
        <data>2018-05-01</data>
        <nome>Dia do Trabalhador</nome>
    </feriado>
</feriados>
